name: Cron Job

on:
  schedule:
    - cron: '*/2 * * * *'  # Runs every minute

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Send message to Slack
        uses: slack/webhook@v5
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          channel: '#awsnotify'  # Replace with the desired Slack channel name
          text: Hello World
