name: Slack Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Run Python script
        run: |
          python hello.py > output.txt
          echo "::set-output name=message::$(cat output.txt)"

      - name: Slack Notification
        uses: act10ns/slack@v1
        with:
          token: ${{ secrets.SLACK_WEBHOOK_URL }}
          channel: '#awsnotify'
          message: ${{ steps.run-python-script.outputs.message }}
