name: Cron Job

on:
  schedule:
    - cron: '*/1 * * * *'  # Runs every minute

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Send message to Slack
<<<<<<< HEAD
        uses: slack/webhook@v5
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          channel: '#awsnotify'  # Replace with the desired Slack channel name
          text: Hello World
=======
        uses: slackapi/python-slack-sdk/send-message@1.3.0
        with:
          channel: awsnotify  # Replace with the desired Slack channel name
          message: Hello World
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
>>>>>>> 2d9eac1ff2497b1d3c1a1c78f5bdc1fde7d752fc
